#!/Users/hammad/.bun/bin/bun

let { argv } = require("process");
const { parse, tokenize } = require("./src/index");
const fs = require("fs")
argv = argv.slice(2, argv.length);
const t0 = performance.now();
const file = argv[0];
if (file) {
  const contents = fs.readFileSync(file)
  const pars = JSON.stringify(parse(tokenize(contents)))
  fs.writeFileSync("ast-" + file + ".json", pars)
  const t1 = performance.now();
  console.log("Generated AST in ", (t1 - t0).toFixed(3), "ms");
} else {
  console.log(
    "Error, source file not specified.\nSyntax:\n\nastgen [file_name]"
  );
}
